#include <windows.h>
#include <stdio.h>
#include <bncs_string.h>
#include <bncs_config.h>
#include "riedel_test.h"

#define PNL_MAIN	1

#define TIMER_SETUP	1

// this nasty little macro to make our class visible to the outside world
EXPORT_BNCS_SCRIPT( riedel_test )

// constructor - equivalent to ApplCore STARTUP
riedel_test::riedel_test( bncs_client_callback * parent, const char * path ) : bncs_script_helper( parent, path )
{
	// show a panel from file p1.bncs_ui and we'll know it as our panel PNL_MAIN
	panelShow( PNL_MAIN, "p1.bncs_ui" );

	// you may need this call to set the size of this component 
	//  if it's used in a popup window 
//	setSize( 1024,668 );		// set the size explicitly
//	setSize( PNL_MAIN );		// set the size to the same as the specified panel

	infoRegister(339, 1, 6);
	infoPoll(339, 1, 6);

}

// destructor - equivalent to ApplCore CLOSEDOWN
riedel_test::~riedel_test()
{
}

// all button pushes and notifications come here
void riedel_test::buttonCallback( buttonNotify *b )
{
	debug(bncs_string("\nbutton id: %1, command: %2, value: %3\n").arg(b->id()).arg(b->command()).arg(b->value()));
	if( b->panel() == PNL_MAIN ) {
		if (b->id() == "sourceGrid" && b->command() == "index") {
			infoRegister(333, b->value(), b->value());
			infoPoll(333, b->value(), b->value());
		} else if (b->id() == "destGrid" && b->command() == "dest") {
			infoRegister(333, b->value() + 2000, b->value() + 2000);
			infoPoll(333, b->value() + 2000, b->value() + 2000);
		}
	}
}

// all revertives come here
int riedel_test::revertiveCallback( revertiveNotify * r )
{
	debug(bncs_string("\nrevertive device: %1, index: %2, value: %3\n").arg(r->device()).arg(r->index()).arg(r->sInfo()));
	if (r->device() == 339) {
		if (r->index() == 6) { // Status
			textPut("text", r->sInfo(), PNL_MAIN, "lblStatus");
		}
		if (r->index() == 1) { // SendString
			textPut("text", r->sInfo(), PNL_MAIN, "lblMessage");
		}
	} else if (r->device() == 333) {
		if (r->index() <= 2001) {
			textPut("text", r->sInfo().replace('|', '*'), PNL_MAIN, "lblSourceUse");
		}
		else {
			textPut("text", r->sInfo().replace('|', '*'), PNL_MAIN, "lblDestUse");
		}
	}
	return 0;
}

// all database name changes come back here
void riedel_test::databaseCallback( revertiveNotify * r )
{
}

// all parent notifications come here i.e. when this script is just one 
//  component of another dialog then our host might want to tell us things
bncs_string riedel_test::parentCallback( parentNotify *p )
{
	if( p->command() == "return" )
	{
		if( p->value() == "all" )
		{	// Persisting values for bncs_vis_ed
			bncs_stringlist sl;
			
			sl << bncs_string( "myParam=%1" ).arg( m_myParam );
			
			return sl.toString( '\n' );
		}

		else if( p->value() == "myParam" )
		{	// Specific value being asked for by a textGet
			return( bncs_string( "%1=%2" ).arg( p->value() ).arg( m_myParam ) );
		}

	}
	else if( p->command() == "instance" && p->value() != m_instance )
	{	// Our instance is being set/changed
		m_instance = p->value();
		//Do something instance-change related here
	}

	else if( p->command() == "myParam" )
	{	// Persisted value or 'Command' being set here
		m_myParam = p->value();
	}

	// ***** CONNECTIONS EVENTS HELPER LIST *****
	else if( p->command() == "_events" )
	{	// Helper-list of everything in this component generated by hostNotify's
		bncs_stringlist sl;

		sl << "notify=*";		
		
		return sl.toString( '\n' );
	}

	// ***** CONNECTIONS COMMANDS HELPER LIST *****
	else if( p->command() == "_commands" )
	{	// Helper-list of any commands/parameters you might want to set at run-time
		bncs_stringlist sl;
		
		sl << "myParam=[value]";
		
		return sl.toString( '\n' );
	}

	return "";
}

// timer events come here
void riedel_test::timerCallback( int id )
{
	switch( id )
	{
	case TIMER_SETUP:
		timerStop(id);
		break;

	default:	// Unhandled timer event
		timerStop(id);
		break;
	}
}


///////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////// Callbacks above - Methods below ///////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////


