#include <windows.h>
#include <stdio.h>
#include <bncs_string.h>
#include <bncs_config.h>
#include "ccu_optics.h"

#define PNL_MAIN	1

#define TIMER_SETUP	1

// this nasty little macro to make our class visible to the outside world
EXPORT_BNCS_SCRIPT( ccu_optics )

// constructor - equivalent to ApplCore STARTUP
ccu_optics::ccu_optics( bncs_client_callback * parent, const char * path ) : bncs_script_helper( parent, path )
{
	// show a panel from file p1.bncs_ui and we'll know it as our panel PNL_MAIN
	panelShow( PNL_MAIN, "p1.bncs_ui" );

	// you may need this call to set the size of this component 
	//  if it's used in a popup window 
//	setSize( 1024,668 );		// set the size explicitly
	setSize( PNL_MAIN );		// set the size to the same as the specified panel
}

// destructor - equivalent to ApplCore CLOSEDOWN
ccu_optics::~ccu_optics()
{
}

// all button pushes and notifications come here
void ccu_optics::buttonCallback( buttonNotify *b )
{

}

// all revertives come here
int ccu_optics::revertiveCallback( revertiveNotify * r )
{
	return 0;
}

// all database name changes come back here
void ccu_optics::databaseCallback( revertiveNotify * r )
{

}

// all parent notifications come here i.e. when this script is just one 
//  component of another dialog then our host might want to tell us things
bncs_string ccu_optics::parentCallback( parentNotify *p )
{
	if( p->command() == "return" )
	{
		if( p->value() == "all" )
		{	// Persisting values for bncs_vis_ed
			bncs_stringlist sl;
			
			sl << bncs_string( "level=%1" ).arg( m_strLevel );
			
			return sl.toString( '\n' );
		}

		else if( p->value() == "level" )
		{	// Specific value being asked for by a textGet
			return( bncs_string( "%1=%2" ).arg( p->value() ).arg( m_strLevel ) );
		}

	}
	else if( p->command() == "instance" && p->value() != m_instance )
	{	// Our instance is being set/changed
		m_instance = p->value();
		//Do something instance-change related here
	}

	else if( p->command() == "level" )
	{	// Persisted value or 'Command' being set here
		m_strLevel = p->value();
		int intLevel = p->value().toInt();
		for (int i = 1; i < 9; i++)
		{
			bncs_string strName = "lbl_led_" + bncs_string(i);
			if (intLevel >= i) {
				controlShow(PNL_MAIN, strName);
			}
			else {
				controlHide(PNL_MAIN, strName);
			}
		}

	}

	// ***** CONNECTIONS EVENTS HELPER LIST *****
	else if( p->command() == "_events" )
	{	// Helper-list of everything in this component generated by hostNotify's
		bncs_stringlist sl;

		sl << "notify=*";		
		
		return sl.toString( '\n' );
	}

	// ***** CONNECTIONS COMMANDS HELPER LIST *****
	else if( p->command() == "_commands" )
	{	// Helper-list of any commands/parameters you might want to set at run-time
		bncs_stringlist sl;
		
		sl << "level=[value]";
		
		return sl.toString( '\n' );
	}

	return "";
}

// timer events come here
void ccu_optics::timerCallback( int id )
{
	switch( id )
	{
	case TIMER_SETUP:
		timerStop(id);
		break;

	default:	// Unhandled timer event
		timerStop(id);
		break;
	}
}


///////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////// Callbacks above - Methods below ///////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////


