#include <windows.h>
#include <stdio.h>
#include <bncs_string.h>
#include <bncs_config.h>
#include "multiviewer.h"

#define MV_PNL	1

#define TIMER_SETUP	1

// this nasty little macro to make our class visible to the outside world
EXPORT_BNCS_SCRIPT( multiviewer )

// constructor - equivalent to ApplCore STARTUP
multiviewer::multiviewer( bncs_client_callback * parent, const char * path ) : bncs_script_helper( parent, path )
{
	m_strMvLayout = "12_way";	// TODO set this to actual layout
	m_strSelectedTile = "";		// no tile selected initially
	panelShow(MV_PNL, bncs_string("layouts/%1.bncs_ui").arg(m_strMvLayout));
	//debug(bncs_string("layouts/%1.bncs_ui\n").arg(m_strMvLayout));

	// you may need this call to set the size of this component 
	//  if it's used in a popup window 
//	setSize( 1024,668 );		// set the size explicitly
	setSize( MV_PNL );		// set the size to the same as the specified panel
}

// destructor - equivalent to ApplCore CLOSEDOWN
multiviewer::~multiviewer()
{
}

// all button pushes and notifications come here
void multiviewer::buttonCallback( buttonNotify *b )
{
	debug(bncs_string("\nb->panel(): %1, b->id(): %2, b->command(): %3, b->value(): %4\n")
		.arg(b->panel()).arg(b->id()).arg(b->command()).arg(b->value()));
	if (b->panel() == MV_PNL)
	{
		bncs_string left, right;
		if (b->id().split('_', left, right) > 0) {
			if (left == "tile") {
				if (b->command() == "command" && b->value() == "selected") {
					m_strSelectedTile = b->id();
				}
			}
		}
	}
}

// all revertives come here
int multiviewer::revertiveCallback( revertiveNotify * r )
{
	//debug(bncs_string("\nr->device(): %1, r->database(): %2, r->index(): %3\n").arg(r->device()).arg(r->database()).arg(r->index()));
	return 0;
}

// all database name changes come back here
void multiviewer::databaseCallback( revertiveNotify * r )
{
}

// all parent notifications come here i.e. when this script is just one 
//  component of another dialog then our host might want to tell us things
bncs_string multiviewer::parentCallback( parentNotify *p )
{
	debug(bncs_string("\np->command(): %1, p->value(): %2\n").arg(p->command()).arg(p->value()));
	if( p->command() == "return" )
	{
		if( p->value() == "all" )
		{	// Persisting values for bncs_vis_ed
			bncs_stringlist sl;
			sl << bncs_string("layout=%1").arg(m_strMvLayout);
			//return "";
			return sl.toString( '\n' );
		}
		else if( p->value() == "layout" )
		{	// Specific value being asked for by a textGet
			return(bncs_string("%1=%2").arg(p->value()).arg(m_strMvLayout));
		}

	}
	else if (p->command() == "instance" && p->value() != m_strInstance) {
		m_strInstance = p->value();
		int startOfMv = m_strInstance.find("_mv");
		bncs_string area = m_strInstance.left(startOfMv);
		bncs_string strMvSettings = bncs_string("%1_multiviewers").arg(area);
		m_strRouter = getObjectSetting(strMvSettings, "router");
		getDev(m_strRouter, &m_intRouterDev);
		m_intDestDatabase = getObjectSetting(strMvSettings, "dest_database");
		m_intDestInstanceDatabase = getObjectSetting(strMvSettings, "dest_instance_database");
		m_intTallyDatabase = getObjectSetting(strMvSettings, "tally_database");
		m_intDestCount = getObjectSetting(m_strInstance, "dest_count");
		m_intFirstDest = getObjectSetting(m_strInstance, "first_dest");
		startInstance();
	}
	else if (p->command() == "layout") {
		debug(bncs_string("p->value(): %1 m_strMvLayout: %2\n").arg(p->value()).arg(m_strMvLayout));
		if (p->value() != m_strMvLayout) {
			m_strMvLayout = p->value();
			panelDestroy(MV_PNL);
			debug(bncs_string("Changing layout to layouts/%1.bncs_ui").arg(m_strMvLayout));
			panelShow(MV_PNL, bncs_string("layouts/%1.bncs_ui").arg(m_strMvLayout));
			setSize(MV_PNL);
			startInstance();
		}
	}
	else if (p->command() == "route_source") {
		if (p->value() >= 0 && m_strSelectedTile != "") {
			textPut("route_source", p->value(), MV_PNL, m_strSelectedTile);
		}
	}

	// ***** CONNECTIONS EVENTS HELPER LIST *****
	else if( p->command() == "_events" )
	{	// Helper-list of everything in this component generated by hostNotify's
		bncs_stringlist sl;

		sl << "notify=*";		
		
		return sl.toString( '\n' );
	}

	// ***** CONNECTIONS COMMANDS HELPER LIST *****
	else if( p->command() == "_commands" )
	{	// Helper-list of any commands/parameters you might want to set at run-time
		bncs_stringlist sl;
		
		//sl << "myParam=[value]";
		//sl << "update=[value]";
		
		return sl.toString( '\n' );
	}

	return "";
}

// timer events come here
void multiviewer::timerCallback( int id ) {
	switch( id )
	{
	case TIMER_SETUP:
		timerStop(id);
		break;

	default:	// Unhandled timer event
		timerStop(id);
		break;
	}
}


///////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////// Callbacks above - Methods below ///////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////

void multiviewer::startInstance() {
	bncs_string strControl;
	int intDestIndex;
	for (int tile = 0; tile < m_intDestCount; tile++) {
		strControl = bncs_string("tile_%1").arg(tile);
		//debug(bncs_string("%1\n").arg(control));
		intDestIndex = m_intFirstDest + tile;
		//debug(bncs_string("%1\n").arg(dest_index));
		textPut("instance", m_strRouter, MV_PNL, strControl);
		textPut("dest_index", intDestIndex, MV_PNL, strControl);
		textPut("dest_database", m_intDestDatabase, MV_PNL, strControl);
		textPut("dest_instance_database", m_intDestInstanceDatabase, MV_PNL, strControl);
		textPut("tally_database", m_intTallyDatabase, MV_PNL, strControl);
		textPut("start", "", MV_PNL, strControl);
	}
	m_strSelectedTile = "";
}
